import type { Metadata } from 'next'
export const metadata:Metadata={title:'RunYourEvent Terms and Conditions',alternates:{canonical:'/terms'}}
const S=({title,children}:{title:string,children:React.ReactNode})=><section><h2 className="text-xl font-black text-[#23324a]">{title}</h2><div className="mt-3 space-y-3 text-sm leading-7 text-[#5f6d80]">{children}</div></section>
export default function Page(){return <main className="bg-[#fbfaf7]"><article className="shell max-w-4xl py-20"><p className="eyebrow">Terms</p><h1 className="display mt-4 text-5xl font-black">Terms & Conditions</h1><p className="mt-5 text-sm text-[#8a93a2]">Last updated: 31 August 2026</p><div className="mt-10 space-y-9">
<S title="1. Provider and scope"><p>RunYourEvent is provided by PlanetHike OÜ, Järvevana tee 9, 11314 Tallinn, Estonia. These terms apply to the RunYourEvent website, event execution plans, Volunteer Engine and related digital services unless a separate written agreement applies.</p></S>
<S title="2. Event execution service"><p>RunYourEvent is an event execution platform. It uses event inputs and structured execution logic, including AI-assisted generation, to produce operating models, tasks, dependencies, timing, approvals, completion criteria, risks and related execution information.</p><p>RunYourEvent is decision-support software. It is not legal, regulatory, engineering, safety, insurance, tax or professional certification advice.</p></S>
<S title="3. Free preview and single-event plans"><p>The free preview is an evaluation view of the event architecture and selected plan information. Essential is USD 19 per event and Professional is USD 39 per event. RunYourEvent does not deliberately remove necessary tasks from an Essential plan merely to force an upgrade.</p></S>
<S title="4. Volunteer Engine"><p>Volunteer Engine is a matching and execution-support service for short volunteer shifts. Seasonal sports-club recruitment is offered at EUR 200 per season. One-off event placement fees are based on successful placements at the rates shown before the organizer proceeds.</p><p>Submitting a volunteer request does not itself create a placement fee. The host organization remains responsible for supervision, briefing, safeguarding, age and role suitability, permissions, safety and compliance with applicable local requirements.</p></S>
<S title="5. Volunteer Protection Plus"><p>Before volunteer placements are activated, the organizer must indicate whether its existing insurance covers temporary or external volunteers for the relevant roles. If equivalent existing cover is confirmed, Volunteer Protection Plus may be selected optionally. If equivalent existing cover is not confirmed, Volunteer Protection Plus is required before placements are activated.</p><p>Volunteer Protection Plus is priced at EUR 1.50 per confirmed volunteer-day when available. Any actual insurance cover is provided or arranged through the connected insurance partner and is subject to that insurer's policy wording, eligibility requirements, exclusions, limits, availability and claims procedures. RunYourEvent does not expand the insurer's contractual coverage and does not guarantee that a particular loss or incident will be insured.</p><p>Selecting insurance does not transfer the organizer's operational, safeguarding, supervision, safety or compliance responsibilities to RunYourEvent.</p></S>
<S title="6. Payment"><p>Payments may be processed by Stripe or another stated payment provider. The price, applicable taxes and total payable amount are shown before a charge is completed. Volunteer Engine protection charges are based on confirmed volunteer-days when applicable and are separate from placement fees.</p></S>
<S title="7. Immediate digital delivery and consumers"><p>Where consumer withdrawal rights apply, RunYourEvent may ask for an express request to begin delivery of digital service/content immediately and an acknowledgement of the consequences before checkout. Statutory rights that cannot lawfully be waived remain unaffected.</p></S>
<S title="8. User responsibilities"><p>You are responsible for the accuracy of information supplied to RunYourEvent and for independently verifying permits, legal requirements, safety measures, insurance, venue rules, supplier commitments, technical specifications and deadlines that could materially affect people, property or compliance.</p></S>
<S title="9. AI and plan accuracy"><p>AI-assisted output can contain omissions, assumptions or errors. RunYourEvent is designed to improve execution structure, not to replace qualified judgement. No guarantee is made that an event will succeed, be profitable, be legally compliant or be free of operational incidents.</p></S>
<S title="10. Licence and intellectual property"><p>Subject to payment, you may use purchased RunYourEvent outputs for the event or organization for which they were generated. RunYourEvent software, branding, product design and underlying system remain the intellectual property of their respective owner/licensor. You may not resell or reproduce RunYourEvent itself as a competing service.</p></S>
<S title="11. Availability"><p>We may maintain, change or improve the service and may suspend access where necessary for security, maintenance, abuse prevention, insurer or partner availability, or legal reasons. We do not promise uninterrupted availability.</p></S>
<S title="12. Liability"><p>Nothing in these terms excludes or limits liability where exclusion is prohibited by applicable law, including liability for intent, gross negligence, or injury to life, body or health where applicable. For ordinary negligence, liability may be limited to breaches of essential contractual duties and foreseeable typical damage to the extent permitted by law. Mandatory consumer rights remain unaffected.</p></S>
<S title="13. Refunds"><p>Refund requests are assessed in light of applicable statutory rights, service-delivery status and the circumstances of the transaction. Contact hello@runyourevent.com with the relevant transaction details.</p></S>
<S title="14. Governing law"><p>These terms are governed by the laws applicable to PlanetHike OÜ without depriving consumers of mandatory protections available under the law of their habitual residence where such protections apply. Mandatory jurisdiction rules remain unaffected.</p></S>
<S title="15. Contact"><p>PlanetHike OÜ · Järvevana tee 9 · 11314 Tallinn · Estonia · hello@runyourevent.com · +49 (0)163 466 8380.</p></S>
</div></article></main>}
